"""empty message

Revision ID: 77ede6fb2e4c
Revises:
Create Date: 2022-08-06 18:28:52.253293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77ede6fb2e4c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artist",
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "show",
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "venue",
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("venue", "date_created")
    op.drop_column("show", "date_created")
    op.drop_column("artist", "date_created")
    # ### end Alembic commands ###
